
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../../src/app/globals.css"
import SideBar from "../../components/SideBar";
import ReduxProvider from "workflo/redux/provider";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
        <div className=" flex w-screen h-screen overflow-hidden">
          <SideBar />
          <div className="w-full h-screen pr-2 flex flex-1 bg-[#edecf5fa] overflow-y-auto overflow-x-hidden">
              {children}
          </div>
        </div>
  );
}
